version: '3'

services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "8001:8001"

  contract-listener-service:
    build:
      context: ./ContractListenerService
      dockerfile: Dockerfile
    image: polkanot/contract-listener-service
    container_name: contract-listener-service
#    ports:
#      - 3000:3000
    volumes:
      - ./ContractListenerService:/ContractListenerService
      - /ContractListenerService/node_modules/
    environment:
      REDIS_URL: 'redis-stack:6379'
