export const subscriber ={
  Address:"xyduaiaufiuifa1203ajb",
  token:"akusfi12ouh452iabf",
  channels:[
    {
      id:"1",
      channel_id:"101",
      name:"Sports",
      lastRead:"09/02/2023 12:10:00",
      webhooks:[ 
        {
          id:"1",
          endpoint:"https//:x.com"
        },
        {
          id:"2",
          endpoint:"https//:y.com"
        },
        {
          id:"3",
          endpoint:"https//:a.com"
        }
      ]
    },
    {
      id:"2",
      channel_id:"102",
      name:"News",
      lastRead:"09/02/2023 17:05:00",
      webhooks:[ 
        {
          id:"1",
          endpoint:"https//:ab.com"
        },
        {
          id:"2",
          endpoint:"https//:ba.com"
        },
        {
          id:"3",
          endpoint:"https//:ac.com"
        }],
    },
    {
      id:"3",
      channel_id:"104",
      name:"Sports",
      lastRead:"09/02/2023 12:10:00",
      webhooks:[ 
        {
          id:"1",
          endpoint:"https//:x.com"
        },
        {
          id:"2",
          endpoint:"https//:y.com"
        },
        {
          id:"3",
          endpoint:"https//:a.com"
        }
      ]
    },
    {
      id:"4",
      channel_id:"104",
      name:"Sports",
      lastRead:"09/02/2023 12:10:00",
      webhooks:[ 
        {
          id:"1",
          endpoint:"https//:x.com"
        },
        {
          id:"2",
          endpoint:"https//:y.com"
        },
        {
          id:"3",
          endpoint:"https//:a.com"
        }
      ]
    },
    {
      id:"5",
      channel_id:"104",
      name:"Sports",
      lastRead:"09/02/2023 12:10:00",
      webhooks:[ 
        {
          id:"1",
          endpoint:"https//:x.com"
        },
        {
          id:"2",
          endpoint:"https//:y.com"
        },
        {
          id:"3",
          endpoint:"https//:a.com"
        }
      ]
    },
    {
      id:"6",
      channel_id:"104",
      name:"Sports",
      lastRead:"09/02/2023 12:10:00",
      webhooks:[ 
        {
          id:"1",
          endpoint:"https//:x.com"
        },
        {
          id:"2",
          endpoint:"https//:y.com"
        },
        {
          id:"3",
          endpoint:"https//:a.com"
        }
      ]
    },
  ],

};

export const ListOfAllChannels =[
  {
    id:"1",
    channel_id:"101",
    name:"channel-1",
    webhooks:[ 
      {
        id:"1",
        endpoint:"https//:x.com"
      },
      {
        id:"2",
        endpoint:"https//:y.com"
      },
      {
        id:"3",
        endpoint:"https//:a.com"
      }
    ]
  },
  {
    id:"2",
    channel_id:"102",
    name:"channel-2",
    webhooks:[ 
      {
        id:"1",
        endpoint:"https//:ab.com"
      },
      {
        id:"2",
        endpoint:"https//:ba.com"
      },
      {
        id:"3",
        endpoint:"https//:ac.com"
      }],
  },
  {
    id:"3",
    channel_id:"103",
    name:"channel-3",
    webhooks:[ 
      {
        id:"1",
        endpoint:"https//:abc.com"
      },
      {
        id:"1",
        endpoint:"https//:bab.com"
      },
      {
        id:"1",
        endpoint:"https//:acg.com"
      }],
  }
];

export const webhooksToDisplay= [
        {
          id:"1",
          endpoint:"https//:x.com"
        },
        {
          id:"2",
          endpoint:"https//:y.com"
        },
        {
          id:"3",
          endpoint:"https//:a.com"
        }
      ];